config-version = 2
start-at-login = true

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

after-startup-command = ['exec-and-forget borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=1.0']

accordion-padding = 45

default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

[key-mapping]
    preset = 'qwerty'

[gaps]
    inner.horizontal = 12
    inner.vertical =   12
    outer.left =       3
    outer.bottom =     3
    outer.top =        3
    outer.right =      3

[mode.main.binding]
    alt-slash = 'layout tiles horizontal vertical'
    alt-comma = 'layout accordion horizontal vertical'

    alt-j = 'focus left'
    alt-k = 'focus down'
    alt-i = 'focus up'
    alt-l = 'focus right'

    alt-shift-j = 'move left'
    alt-shift-k = 'move down'
    alt-shift-i = 'move up'
    alt-shift-l = 'move right'

    alt-1 = 'workspace 1'
    alt-2 = 'workspace 2'
    alt-3 = 'workspace 3'
    alt-4 = 'workspace 4'
    alt-5 = 'workspace 5'
    alt-6 = 'workspace 6'
    alt-7 = 'workspace 7'
    alt-8 = 'workspace 8'
    alt-9 = 'workspace 9'

    alt-shift-1 = 'move-node-to-workspace 1'
    alt-shift-2 = 'move-node-to-workspace 2'
    alt-shift-3 = 'move-node-to-workspace 3'
    alt-shift-4 = 'move-node-to-workspace 4'
    alt-shift-5 = 'move-node-to-workspace 5'
    alt-shift-6 = 'move-node-to-workspace 6'
    alt-shift-7 = 'move-node-to-workspace 7'
    alt-shift-8 = 'move-node-to-workspace 8'
    alt-shift-9 = 'move-node-to-workspace 9'

    alt-tab = 'workspace-back-and-forth'
    alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

    alt-shift-semicolon = 'mode service'
    alt-shift-r = 'mode resize'

[mode.resize.binding]
    j = 'resize smart -50'
    k = 'resize smart -50'
    r = 'flatten-workspace-tree'
    enter = 'mode main'
    esc = 'mode main'


[mode.service.binding]
    esc = ['reload-config', 'mode main']
    f = ['layout floating tiling', 'mode main']
    backspace = ['close-all-windows-but-current', 'mode main']

    alt-shift-j = ['join-with left', 'mode main']
    alt-shift-k = ['join-with down', 'mode main']
    alt-shift-i = ['join-with up', 'mode main']
    alt-shift-l = ['join-with right', 'mode main']
    alt-shift-f = ['fullscreen --no-outer-gaps', 'mode main']
